# Add your API keys here
OPENAI_API_KEY = "your-openai-api-key-here"
ANTHROPIC_API_KEY = "your-claude-api-key-here"

# For deployment, add these as secrets in Streamlit Cloud, I will add the keys later